/**
 * prompt.js — Prompt template builders for ReviewPilot's AI response generation.
 *
 * Builds structured prompts for different review scenarios:
 * - positive / neutral / negative sentiment
 * - each with appropriate tone, structure, and guardrails
 *
 * Exports builder functions that take business + review context and return
 * arrays of { role, content } messages ready to send to OpenAI or Claude.
 */

// ─── Sentiment Helpers ───────────────────────────────────────────────────────

/**
 * Classify a star rating into a sentiment bucket.
 * @param {number} rating - 1-5 star rating
 * @returns {'positive'|'neutral'|'negative'}
 */
export function classifySentiment(rating) {
  if (rating >= 4) return 'positive';
  if (rating === 3) return 'neutral';
  return 'negative';
}

// ─── System Prompt ───────────────────────────────────────────────────────────

/**
 * Build the system prompt that sets the AI's role, brand context, and rules.
 * @param {object} context
 * @param {string} context.businessName
 * @param {string} context.businessType  - e.g. "dental clinic", "auto repair shop"
 * @param {string} [context.brandVoice]  - e.g. "professional", "warm", "casual"
 * @param {string} [context.signatureStyle] - "first-person" | "we" | "business-name"
 * @param {string} [context.customInstructions] - free-text additional rules
 * @param {string[]} [context.avoidTopics] - topics to avoid mentioning
 * @param {number} [context.totalReviewCount]
 * @param {number} [context.averageRating]
 * @returns {string} the system prompt
 */
export function buildSystemPrompt(context) {
  const {
    businessName,
    businessType,
    brandVoice = 'professional',
    signatureStyle = 'we',
    customInstructions = '',
    avoidTopics = [],
    totalReviewCount,
    averageRating,
  } = context;

  let signWith;
  switch (signatureStyle) {
    case 'first-person':
      signWith = 'I';
      break;
    case 'business-name':
      signWith = businessName;
      break;
    case 'we':
    default:
      signWith = 'We';
  }

  const avoidSection = avoidTopics.length
    ? `\nAVOID mentioning these topics: ${avoidTopics.join(', ')}.`
    : '';

  const statsSection =
    totalReviewCount !== undefined && averageRating !== undefined
      ? `\n(This business has ${totalReviewCount} total reviews with an average of ${averageRating.toFixed(1)} stars.)`
      : '';

  return `You are ReviewPilot, an AI assistant that helps local service businesses craft authentic, personalized responses to customer reviews. You write in the business owner's voice.

BUSINESS CONTEXT:
- Business Name: ${businessName}
- Business Type: ${businessType}
- Brand Voice: ${brandVoice}
- Signature Style: Sign with "${signWith}"${statsSection}

CORE RULES:
1. Be specific — reference details the reviewer mentioned (what they liked or didn't like)
2. Be authentic — never sound like a template or form letter
3. Be concise — maximum 180 words${avoidSection}
4. Use natural language — no markdown, no emoji, no hashtags
5. Never mention: "ReviewPilot", "AI", "automated response", "generated by"

${customInstructions}

TONE GUIDELINES BY RATING:
- 4-5 stars: Warm, grateful, affirming. Match the reviewer's enthusiasm.
- 3 stars: Appreciative, receptive, open. Thank them for balanced feedback.
- 1-2 stars: Empathetic, accountable, solution-oriented. Apologize sincerely. Offer to make it right. NEVER be defensive or dismissive.`;
}

// ─── Review Prompt Builder ───────────────────────────────────────────────────

/**
 * Build the user message containing the review details for the AI to respond to.
 * @param {object} review
 * @param {number} review.rating - 1-5
 * @param {string} review.comment - review text
 * @param {string} [review.reviewerName] - optional reviewer display name
 * @param {string} [review.reviewDate] - optional date string
 * @returns {string} the user prompt
 */
export function buildReviewPrompt(review) {
  const { rating, comment, reviewerName = 'a customer', reviewDate = '' } = review;
  const dateLine = reviewDate ? `\nReview Date: ${reviewDate}` : '';

  return `Please write a response to this review:

Rating: ${rating}/5
Reviewer: ${reviewerName}
Review: "${comment}"${dateLine}

Write the response now. Return ONLY the response text — nothing else.`;
}

// ─── Advanced: Structured Output Prompt ──────────────────────────────────────

/**
 * Build a prompt that asks the AI to return BOTH a response draft AND
 * a sentiment/urgency analysis in a predictable format.
 * Useful when we want to capture metadata without a second API call.
 */
export function buildAnalysisPrompt(review, context) {
  const { rating, comment, reviewerName = 'a customer' } = review;
  const { businessName, businessType } = context;

  return [
    {
      role: 'system',
      content: buildSystemPrompt(context),
    },
    {
      role: 'user',
      content: `Analyze this review and generate a response.

REVIEW:
Business: ${businessName} (${businessType})
Rating: ${rating}/5
Reviewer: ${reviewerName}
Review: "${comment}"

Respond in this exact JSON format (no other text):
{
  "sentiment": "positive|neutral|negative",
  "urgency": "low|medium|high",
  "key_themes": ["theme1", "theme2"],
  "draft_response": "Your generated response here"
}

Guidelines for the analysis fields:
- "sentiment": positive (4-5★), neutral (3★), negative (1-2★)
- "urgency": high if business name/reputation is at risk or safety concern; medium if notable complaint; low for positive
- "key_themes": extract 1-3 main topics from the review (e.g., "wait times", "quality", "pricing", "service")
- "draft_response": the full response following the brand voice rules`,
    },
  ];
}

// ─── Variant: Negative Review (Empathetic + Problem-Solving) ─────────────────

/**
 * Get additional instructions appended for negative reviews.
 */
export function getNegativeReviewExtension() {
  return `\n\nIMPORTANT — This is a negative review. Follow these guidelines:
1. Acknowledge the customer's specific complaint — show you truly read it
2. Apologize sincerely and take ownership
3. Briefly explain any corrective action (if appropriate)
4. Offer to connect offline (e.g., "please call us at [phone]" or "email us") to resolve personally
5. Thank them for the feedback — it helps the business improve
DO NOT: make excuses, blame the customer, become defensive, or use legal/corporate language.`;
}

// ─── Variant: Positive Review (Short + Warm) ─────────────────────────────────

/**
 * Get additional instructions appended for positive reviews (shorter response).
 */
export function getPositiveReviewExtension() {
  return `\n\nIMPORTANT — This is a positive review. Write a short, warm response:
1. Thank the reviewer by name
2. Reference something specific they complimented
3. Express appreciation and invite them back
Keep it to 2-3 sentences, under 80 words.`;
}

// ─── Full Message Builder ────────────────────────────────────────────────────

/**
 * Build the complete message array ready to send to the LLM.
 * @param {object} context - business context (see buildSystemPrompt)
 * @param {object} review - review details (see buildReviewPrompt)
 * @returns {{ messages: Array<{role:string, content:string}>, extraInstructions?: string }}
 */
export function buildMessages(context, review) {
  const sentiment = classifySentiment(review.rating);
  const systemPrompt = buildSystemPrompt(context);

  // Append rating-specific extensions
  let extraInstructions = '';
  if (sentiment === 'negative') {
    extraInstructions = getNegativeReviewExtension();
  } else if (sentiment === 'positive') {
    extraInstructions = getPositiveReviewExtension();
  }

  const reviewPrompt = buildReviewPrompt(review) + extraInstructions;

  return {
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: reviewPrompt },
    ],
    sentiment,
  };
}